import type { Report } from "./types";

const DISCORD_API = "https://discord.com/api/v10";

export type DiscordPayload = {
  botToken: string;
  channelId: string;
  applicantName?: string;
  applicantEmail?: string;
  report: Report;
  pdf: Uint8Array;
};

export type DiscordResult = { messageId: string; timestamp: string };

// Discord embed field values cap at 1024 chars.
function trunc(s: string, max = 1000): string {
  return s.length > max ? s.slice(0, max - 1) + "…" : s;
}

function bullets(items: string[], max = 6): string {
  if (!items.length) return "—";
  return trunc(items.slice(0, max).map((i) => `• ${i}`).join("\n"));
}

// Translate a Discord HTTP failure into an actionable message for the evaluator.
function explain(status: number, raw: string): string {
  if (status === 401) return "Invalid bot token (401). Check the token in Settings → Discord.";
  if (status === 403) return "Bot lacks permission to post/attach in this channel (403). Invite the bot and grant Send Messages + Attach Files.";
  if (status === 404) return "Channel not found (404). Check the Channel ID.";
  if (status === 429) return "Rate limited by Discord (429). Try again in a moment.";
  return `Discord error ${status}: ${raw.slice(0, 160)}`;
}

// Send a rich research report embed + PDF attachment to a Discord channel.
export async function sendToDiscord(p: DiscordPayload): Promise<DiscordResult> {
  const c = p.report.company;
  const fields = [
    { name: "👤 Applicant", value: p.applicantName || "—", inline: true },
    { name: "✉️ Email", value: p.applicantEmail || "—", inline: true },
    { name: "🌐 Website", value: c.website || "—", inline: false },
  ];
  if (c.products.length) fields.push({ name: "🧩 Products / Services", value: bullets(c.products), inline: false });
  if (c.painPoints.length) fields.push({ name: "⚠️ Pain Points", value: bullets(c.painPoints, 4), inline: false });
  if (p.report.competitors.length)
    fields.push({
      name: "🎯 Competitors",
      value: trunc(p.report.competitors.slice(0, 6).map((x) => `• ${x.name}${x.website ? ` — ${x.website}` : ""}`).join("\n")),
      inline: false,
    });

  const embed = {
    title: c.name,
    url: c.website || undefined,
    description: trunc(c.summary || "Company research report.", 300),
    color: 0x0066cc,
    thumbnail: p.report.logo ? { url: p.report.logo } : undefined,
    fields,
    footer: { text: "Generated by Scout · Relu Hiring Challenge" },
    timestamp: new Date().toISOString(),
  };

  const form = new FormData();
  form.append("payload_json", JSON.stringify({ content: "📊 New company research report generated.", embeds: [embed] }));

  const safeName = (c.name || "company").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const blob = new Blob([p.pdf as BlobPart], { type: "application/pdf" });
  form.append("files[0]", blob, `${safeName}-research-report.pdf`);

  const res = await fetch(`${DISCORD_API}/channels/${p.channelId}/messages`, {
    method: "POST",
    headers: { Authorization: `Bot ${p.botToken}` },
    body: form,
    signal: AbortSignal.timeout(30000),
  });

  if (!res.ok) {
    throw new Error(explain(res.status, await res.text().catch(() => "")));
  }
  const msg = (await res.json().catch(() => ({}))) as { id?: string; timestamp?: string };
  return { messageId: msg.id || "", timestamp: msg.timestamp || new Date().toISOString() };
}
